jupiter-legacy-support-1.139-1-any.pkg.tar.zst
Archive sha256sum: 8b8dbc1f62f5775139bf5587c32e1a08bad00544ef8b37792d806ac256e26688 jupiter-legacy-support-1.139-1-any.pkg.tar.zst

diff --git a/bin/steamos-update b/bin/steamos-update
--- a/bin/steamos-update
+++ b/bin/steamos-update
@@ -6,13 +6,22 @@ set -eu
 ## This script must match the API the temporary Steam UI updater wants of us, including this file
 ##
 
+BRANCH_PATH="/var/lib/steamos-branch"
+CI_HOST_PATH="/var/lib/steamos-branch-ci-host"
+CI_KEY_PATH="/var/lib/steamos-branch-ci-key"
+
+# ci builds can bake these in as defaults
+[[ -e $BRANCH_PATH ]] || BRANCH_PATH="/usr/lib/steamos/default-branch"
+[[ -e $CI_HOST_PATH ]] || CI_HOST_PATH="/usr/lib/steamos/default-branch-ci-host"
+[[ -e $CI_KEY_PATH ]] || CI_KEY_PATH="/usr/lib/steamos/default-branch-ci-key"
+
 unset tmpdir
 cleanup() { rm -rf /tmp/steamos-update.pid; [[ -z ${tmpdir-} ]] || rm -rf --one-file-system -- "$tmpdir"; }
 trap cleanup EXIT
 touch /tmp/steamos-update.pid
+
 info() { echo >&2 "$*"; }
 die() { info "!! $*"; exit 1; }
-
 
 checkmode=""
 error=""
@@ -37,19 +46,49 @@ if [[ -n $error ]]; then
   exit 1
 fi
 
+atomupd_args=(--manifest "/usr/share/steamos-update/manifest-0.json")
+[[ -n $debug ]] && atomupd_args+=(-d)
+
+##
+## CI hook, if this file exists use that CI endpoint
+##
+ci_host=
+if [[ -e $CI_HOST_PATH && -e $CI_KEY_PATH ]]; then
+  ci_host=$(cat -- "$CI_HOST_PATH" || true)
+  ci_key=$(cat -- "$CI_KEY_PATH" || true)
+  [[ $ci_host =~ ^[0-9a-zA-Z]+$ ]] || die "Bad CI branch name"
+  [[ $ci_key =~ ^[0-9a-zA-Z]+$ ]] || die "Bad CI branch name"
+  [[ -n ${tmpdir-} ]] || tmpdir="$(mktemp -d --tmp steamos-update.XXX)" || die "Could not create temporary directory"
+
+  # Make stub netrc and client conf files
+  ci_conf="$tmpdir"/ci_conf.conf
+  cfg=$(sed -r 's/(https:\/\/)([^-/]+)-(images|atomupd)/\1'"$ci_host"'-\3/g' /etc/steamos-atomupd/client.conf)
+  cat <<<"$cfg" >"$ci_conf"
+
+  # Register in netrc.
+  for host in images atomupd packages; do
+    if ! grep -q "^machine $ci_host-$host.steamos.cloud " /root/.netrc 2>/dev/null; then
+      echo "machine $ci_host-$host.steamos.cloud login atomupd-ci-client password $ci_key" >> /root/.netrc
+    fi
+  done
+
+  atomupd_args+=(-d --config "$ci_conf")
+fi
+## End CI hook
+
 # Determine which branches to check.
 check_rel=0
 check_rc=0
 check_beta=0
 check_bc=0
 check_main=0
+check_staging=0
 
 if [[ -n $beta ]]; then
   info "'--beta' is deprecated; use 'steamos-select-branch beta' then 'steamos-update'"
   check_beta=1
 else
-  branch_path="/var/lib/steamos-branch"
-  branch=$(cat "$branch_path" 2> /dev/null || echo "rel")
+  branch=$(cat "$BRANCH_PATH" 2> /dev/null || echo "rel")
   case "$branch" in
     "rel")
       check_rel=1
@@ -68,9 +107,14 @@ else
     "main")
       check_main=1
       ;;
+    "staging")
+      check_staging=1
+      ;;
     *)
-      echo "unknown branch name in $branch_path: $branch" 1>&2
-      exit 1
+      if [[ -z $ci_host ]]; then # CI branches are arbitrary
+        echo "unknown branch name in $BRANCH_PATH: $branch" 1>&2
+        exit 1
+      fi
       ;;
   esac
 fi
@@ -81,9 +125,7 @@ get_buildid () {
     exit 0
   fi
 
-  atomupd_args=(--variant="$2" --query-only)
-  [[ -n $debug ]] && atomupd_args+=(-d)
-  query="$(sudo steamos-atomupd-client "${atomupd_args[@]}")"
+  query="$(sudo steamos-atomupd-client "${atomupd_args[@]}" --variant="$2" --query-only)"
   if [[ -z $query ]]; then
     info "Failed to check for updates"
     exit 1 # Unknown failure
@@ -92,11 +134,17 @@ get_buildid () {
   jq -r '.minor.candidates[0].image.buildid | select(type == "string")' <<< "$query"
 }
 
+buildid_ci=
+if [[ -n $ci_host ]]; then
+  buildid_ci="$(get_buildid 1 steamdeck-"$branch")"
+fi
+
 buildid_rel="$(get_buildid $check_rel steamdeck)"
 buildid_rc="$(get_buildid $check_rc steamdeck-rc)"
 buildid_beta="$(get_buildid $check_beta steamdeck-beta)"
 buildid_bc="$(get_buildid $check_bc steamdeck-bc)"
 buildid_main="$(get_buildid $check_main steamdeck-main)"
+buildid_staging="$(get_buildid $check_staging steamdeck-staging)"
 
 if [[ -n $debug ]]; then
   info "buildid_rel=$buildid_rel"
@@ -104,6 +152,8 @@ if [[ -n $debug ]]; then
   info "buildid_beta=$buildid_beta"
   info "buildid_bc=$buildid_bc"
   info "buildid_main=$buildid_main"
+
+  [[ -n $ci_host ]] && info "buildid_ci=$buildid_ci"
 fi
 
 # Choose the variant with the newest buildid.
@@ -130,8 +180,23 @@ if [[ "$buildid_main" > "$chosen_buildid" ]]; then
   chosen_buildid="$buildid_main"
   chosen_variant="steamdeck-main"
 fi
+if [[ "$buildid_staging" > "$chosen_buildid" ]]; then
+  chosen_buildid="$buildid_staging"
+  chosen_variant="steamdeck-staging"
+fi
+if [[ "$buildid_ci" > "$chosen_buildid" ]]; then
+  chosen_buildid="$buildid_ci"
+  chosen_variant="steamdeck-$branch"
+fi
 
 if [[ -z "$chosen_variant" ]]; then
+  info "No update available"
+  exit 7
+fi
+
+manifest_path="/etc/steamos-atomupd/manifest.json"
+current_buildid=$(jq -r .buildid < "$manifest_path")
+if [[ "$current_buildid" = "$chosen_buildid" ]]; then
   info "No update available"
   exit 7
 fi
@@ -151,9 +216,7 @@ if [[ -n ${checkmode-} ]]; then
 fi
 
 # Not check mode. Update!
-atomupd_args=(--variant="$chosen_variant")
-[[ -n $debug ]] && atomupd_args+=(-d)
-do_atomupd() { sudo steamos-atomupd-client "${atomupd_args[@]}" "$@"; }
+do_atomupd() { sudo steamos-atomupd-client "${atomupd_args[@]}" --variant="$chosen_variant" "$@"; }
 
 if do_atomupd; then
   info "Applied an update"
