jupiter-legacy-support-1.139-2-any.pkg.tar.zst
Archive sha256sum: 6a27aeceb501d9bb17de338f0ad8c6639ad5f295a58398ac8ab7a791edb40f83 jupiter-legacy-support-1.139-2-any.pkg.tar.zst

diff --git a/bin/steamos-update b/bin/steamos-update
--- a/bin/steamos-update
+++ b/bin/steamos-update
@@ -6,24 +6,45 @@ set -eu
 ## This script must match the API the temporary Steam UI updater wants of us, including this file
 ##
 
+BRANCH_PATH="/var/lib/steamos-branch"
+CI_HOST_PATH="/var/lib/steamos-branch-ci-host"
+CI_KEY_PATH="/var/lib/steamos-branch-ci-key"
+
+# ci builds can bake these in as defaults
+[[ -e $BRANCH_PATH ]] || BRANCH_PATH="/usr/lib/steamos/default-branch"
+[[ -e $CI_HOST_PATH ]] || CI_HOST_PATH="/usr/lib/steamos/default-branch-ci-host"
+[[ -e $CI_KEY_PATH ]] || CI_KEY_PATH="/usr/lib/steamos/default-branch-ci-key"
+
 unset tmpdir
 cleanup() { rm -rf /tmp/steamos-update.pid; [[ -z ${tmpdir-} ]] || rm -rf --one-file-system -- "$tmpdir"; }
 trap cleanup EXIT
 touch /tmp/steamos-update.pid
+
 info() { echo >&2 "$*"; }
 die() { info "!! $*"; exit 1; }
+
+# Please keep these in sync with steamos-customizations pre-install and
+# post-install
+STEAMOS_ATOMUPD_RUNTIME_DIR=/run/steamos-atomupd
+REBOOT_FOR_UPDATE=reboot_for_update
 
 
 checkmode=""
 error=""
 beta=""
 debug=""
+duplicate_detection=""
 
 while [[ $# -ge 1 ]]; do
   case "$1" in
     "check") checkmode=1 ;;
     "--beta") beta=1 ;;
     "-d") debug=1 ;;
+    "--enable-duplicate-detection") duplicate_detection=1 ;;
+    "--supports-duplicate-detection")
+      info "This script supports the duplicate detection option"
+      exit 0
+    ;;
     *)
       error=1
       info "Unknown option \"$1\""
@@ -37,8 +58,35 @@ if [[ -n $error ]]; then
   exit 1
 fi
 
-atomupd_args=(--manifest "/usr/share/steamos-update/manifest-0.json")
+atomupd_args=()
 [[ -n $debug ]] && atomupd_args+=(-d)
+
+##
+## CI hook, if this file exists use that CI endpoint
+##
+ci_host=
+if [[ -e $CI_HOST_PATH && -e $CI_KEY_PATH ]]; then
+  ci_host=$(cat -- "$CI_HOST_PATH" || true)
+  ci_key=$(cat -- "$CI_KEY_PATH" || true)
+  [[ $ci_host =~ ^[0-9a-zA-Z]+$ ]] || die "Bad CI branch name"
+  [[ $ci_key =~ ^[0-9a-zA-Z]+$ ]] || die "Bad CI branch name"
+  [[ -n ${tmpdir-} ]] || tmpdir="$(mktemp -d --tmp steamos-update.XXX)" || die "Could not create temporary directory"
+
+  # Make stub netrc and client conf files
+  ci_conf="$tmpdir"/ci_conf.conf
+  cfg=$(sed -r 's/(https:\/\/)([^-/]+)-(images|atomupd)/\1'"$ci_host"'-\3/g' /etc/steamos-atomupd/client.conf)
+  cat <<<"$cfg" >"$ci_conf"
+
+  # Register in netrc.
+  for host in images atomupd packages; do
+    if ! grep -q "^machine $ci_host-$host.steamos.cloud " /root/.netrc 2>/dev/null; then
+      echo "machine $ci_host-$host.steamos.cloud login atomupd-ci-client password $ci_key" >> /root/.netrc
+    fi
+  done
+
+  atomupd_args+=(-d --config "$ci_conf")
+fi
+## End CI hook
 
 # Determine which branches to check.
 check_rel=0
@@ -46,13 +94,13 @@ check_rc=0
 check_beta=0
 check_bc=0
 check_main=0
+check_staging=0
 
 if [[ -n $beta ]]; then
   info "'--beta' is deprecated; use 'steamos-select-branch beta' then 'steamos-update'"
   check_beta=1
 else
-  branch_path="/var/lib/steamos-branch"
-  branch=$(cat "$branch_path" 2> /dev/null || echo "rel")
+  branch=$(cat "$BRANCH_PATH" 2> /dev/null || echo "rel")
   case "$branch" in
     "rel")
       check_rel=1
@@ -71,9 +119,14 @@ else
     "main")
       check_main=1
       ;;
+    "staging")
+      check_staging=1
+      ;;
     *)
-      echo "unknown branch name in $branch_path: $branch" 1>&2
-      exit 1
+      if [[ -z $ci_host ]]; then # CI branches are arbitrary
+        echo "unknown branch name in $BRANCH_PATH: $branch" 1>&2
+        exit 1
+      fi
       ;;
   esac
 fi
@@ -85,7 +138,10 @@ get_buildid () {
   fi
 
   query="$(sudo steamos-atomupd-client "${atomupd_args[@]}" --variant="$2" --query-only)"
-  if [[ -z $query ]]; then
+  # If there is an update candidate, `query` will hold the update JSON.
+  # If there isn't an update, `query` will be empty.
+  # Finally, a non-zero return code means that an error occurred.
+  if [[ $? != 0 ]]; then
     info "Failed to check for updates"
     exit 1 # Unknown failure
   fi
@@ -93,11 +149,17 @@ get_buildid () {
   jq -r '.minor.candidates[0].image.buildid | select(type == "string")' <<< "$query"
 }
 
+buildid_ci=
+if [[ -n $ci_host ]]; then
+  buildid_ci="$(get_buildid 1 steamdeck-"$branch")"
+fi
+
 buildid_rel="$(get_buildid $check_rel steamdeck)"
 buildid_rc="$(get_buildid $check_rc steamdeck-rc)"
 buildid_beta="$(get_buildid $check_beta steamdeck-beta)"
 buildid_bc="$(get_buildid $check_bc steamdeck-bc)"
 buildid_main="$(get_buildid $check_main steamdeck-main)"
+buildid_staging="$(get_buildid $check_staging steamdeck-staging)"
 
 if [[ -n $debug ]]; then
   info "buildid_rel=$buildid_rel"
@@ -105,6 +167,8 @@ if [[ -n $debug ]]; then
   info "buildid_beta=$buildid_beta"
   info "buildid_bc=$buildid_bc"
   info "buildid_main=$buildid_main"
+
+  [[ -n $ci_host ]] && info "buildid_ci=$buildid_ci"
 fi
 
 # Choose the variant with the newest buildid.
@@ -131,6 +195,14 @@ if [[ "$buildid_main" > "$chosen_buildid" ]]; then
   chosen_buildid="$buildid_main"
   chosen_variant="steamdeck-main"
 fi
+if [[ "$buildid_staging" > "$chosen_buildid" ]]; then
+  chosen_buildid="$buildid_staging"
+  chosen_variant="steamdeck-staging"
+fi
+if [[ "$buildid_ci" > "$chosen_buildid" ]]; then
+  chosen_buildid="$buildid_ci"
+  chosen_variant="steamdeck-$branch"
+fi
 
 if [[ -z "$chosen_variant" ]]; then
   info "No update available"
@@ -142,6 +214,16 @@ current_buildid=$(jq -r .buildid < "$manifest_path")
 if [[ "$current_buildid" = "$chosen_buildid" ]]; then
   info "No update available"
   exit 7
+fi
+
+# Do this check only if explicitly enabled to avoid returning a new exit code
+# that the Steam client doesn't support yet
+if [[ -f "$STEAMOS_ATOMUPD_RUNTIME_DIR/$REBOOT_FOR_UPDATE" && -n $duplicate_detection ]]; then
+  installed_buildid=$(< "$STEAMOS_ATOMUPD_RUNTIME_DIR/$REBOOT_FOR_UPDATE")
+  if [[ "$installed_buildid" = "$chosen_buildid" ]]; then
+    info "Update $chosen_buildid has already been applied, please reboot to enable it"
+    exit 8
+  fi
 fi
 
 if [[ -n $debug ]]; then
