jupiter-legacy-support-1.137-1-any
Archive sha256sum: 8e14ede1d0a297aefa900054c35ca58d0c2fc226f179db90822e770c934aa47a jupiter-legacy-support-1.137-1-any.pkg.tar.zst

diff --git a/bin/steamos-select-branch b/bin/steamos-select-branch
--- a/bin/steamos-select-branch
+++ b/bin/steamos-select-branch
@@ -2,8 +2,36 @@
 set -e
 
 BRANCH_PATH="/var/lib/steamos-branch"
+CI_HOST_PATH="/var/lib/steamos-branch-ci-host"
+CI_KEY_PATH="/var/lib/steamos-branch-ci-key"
 
-if [[ "$#" = 1 ]]; then
+# CI mode hook, target alternate environment
+ci_branch=
+ci_key=
+if [[ $# -ge 2 && $1 = "--ci-env" ]]; then
+  ci_env=${2-}
+  ci_branch=${ci_env%%:*}
+  ci_key=${ci_env#*:}
+  if [[ -z $ci_branch || -z $ci_key || $ci_branch = $ci_env || $ci_key = $ci_env ]]; then
+    echo "Invalid usage of --ci-env, expect ciname:key"
+    exit 1
+  fi
+  if ! [[ $ci_key =~ ^[0-9a-zA-Z]+$ && $ci_branch =~ ^[0-9a-zA-Z]+$ ]]; then
+    echo "Bad CI key/branch"
+    exit 1
+  fi
+
+  echo "$ci_branch" > "$CI_HOST_PATH"
+  echo "$ci_key" > "$CI_KEY_PATH"
+
+  # If no other branch/command given, select ci name as default branch
+  if [[ $# -eq 2 ]]; then
+    echo "$ci_branch" > "$BRANCH_PATH"
+    exit 0
+  fi
+fi
+
+if [[ $# -eq 1 ]]; then
   case "$1" in
     "-c")
       branch=$(cat "$BRANCH_PATH" 2> /dev/null || echo "rel")
