jupiter-legacy-support-1.139-2-any
Archive sha256sum: 6a27aeceb501d9bb17de338f0ad8c6639ad5f295a58398ac8ab7a791edb40f83 jupiter-legacy-support-1.139-2-any.pkg.tar.zst

diff --git a/bin/steamos-update b/bin/steamos-update
--- a/bin/steamos-update
+++ b/bin/steamos-update
@@ -23,16 +23,28 @@ touch /tmp/steamos-update.pid
 info() { echo >&2 "$*"; }
 die() { info "!! $*"; exit 1; }
 
+# Please keep these in sync with steamos-customizations pre-install and
+# post-install
+STEAMOS_ATOMUPD_RUNTIME_DIR=/run/steamos-atomupd
+REBOOT_FOR_UPDATE=reboot_for_update
+
+
 checkmode=""
 error=""
 beta=""
 debug=""
+duplicate_detection=""
 
 while [[ $# -ge 1 ]]; do
   case "$1" in
     "check") checkmode=1 ;;
     "--beta") beta=1 ;;
     "-d") debug=1 ;;
+    "--enable-duplicate-detection") duplicate_detection=1 ;;
+    "--supports-duplicate-detection")
+      info "This script supports the duplicate detection option"
+      exit 0
+    ;;
     *)
       error=1
       info "Unknown option \"$1\""
@@ -46,7 +58,7 @@ if [[ -n $error ]]; then
   exit 1
 fi
 
-atomupd_args=(--manifest "/usr/share/steamos-update/manifest-0.json")
+atomupd_args=()
 [[ -n $debug ]] && atomupd_args+=(-d)
 
 ##
@@ -126,7 +138,10 @@ get_buildid () {
   fi
 
   query="$(sudo steamos-atomupd-client "${atomupd_args[@]}" --variant="$2" --query-only)"
-  if [[ -z $query ]]; then
+  # If there is an update candidate, `query` will hold the update JSON.
+  # If there isn't an update, `query` will be empty.
+  # Finally, a non-zero return code means that an error occurred.
+  if [[ $? != 0 ]]; then
     info "Failed to check for updates"
     exit 1 # Unknown failure
   fi
@@ -199,6 +214,16 @@ current_buildid=$(jq -r .buildid < "$manifest_path")
 if [[ "$current_buildid" = "$chosen_buildid" ]]; then
   info "No update available"
   exit 7
+fi
+
+# Do this check only if explicitly enabled to avoid returning a new exit code
+# that the Steam client doesn't support yet
+if [[ -f "$STEAMOS_ATOMUPD_RUNTIME_DIR/$REBOOT_FOR_UPDATE" && -n $duplicate_detection ]]; then
+  installed_buildid=$(< "$STEAMOS_ATOMUPD_RUNTIME_DIR/$REBOOT_FOR_UPDATE")
+  if [[ "$installed_buildid" = "$chosen_buildid" ]]; then
+    info "Update $chosen_buildid has already been applied, please reboot to enable it"
+    exit 8
+  fi
 fi
 
 if [[ -n $debug ]]; then
